### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by artiy** [graphhopper/graphhopper-ios#16] opened 2017-04-04 07:29 UTC
I am trying to run graphhopper sample project on my m/c. I downloaded sample project and followed each and every step as directed in elow link

https://github.com/graphhopper/graphhopper-ios#usage 

and then followed to resolve some shell script issues

https://github.com/graphhopper/graphhopper-ios/issues/12

but still I am getting following issues

ld: warning: -L path '/Users/xeliumtech/Documents/ArtiProjects/graphhopper-ios/build/libgraphhopper.a' is not a directory
ld: library not found for -lgraphhopper
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Need help. I am also attaching my projct structure 
![screen shot 2017-04-04 at 12 58 06 pm](https://cloud.githubusercontent.com/assets/5718195/24645606/71ced39a-1936-11e7-9360-082bf4925c8d.png)

**Comment by karussell** [comment] 2017-04-04 07:31
Duplicate of #15

**Closed by karussell** 2017-04-04 07:31 UTC
